### ISSUE TITLE
Error migrate laravel data with docker postgresql

### ISSUE THREAD

**Issue by kilwir76** [WebDB-App/app#17]
![image](https://github.com/WebDB-App/app/assets/13037707/62ccf0c1-f6aa-4c2c-9627-a9e802b0d828)

**Comment by kilwir76** [comment]
i don't understand , with adminer its ok

**Comment by WebDB-App** [comment]
Is it better now ?

**Comment by WebDB-App** [comment]
?

**Comment by WebDB-App** [comment]
Think of hard reset cache (right click on the refresh icon)

**Comment by WebDB-App** [comment]
Very sorry for the inconvenience. It's truly fixed now
