### ISSUE TITLE
Unable to 'forget' or update db connection

### ISSUE THREAD

**Issue by wrgrant** [WebDB-App/app#19]
Using latest safari v17.1.2

I changed the hostname for my mongo db in my docker compose solution.

In the WebDB interface, when I try to update an existing connection, it fails.

When I try to add a new connection, it fails.

Here is a video showing the behavior.

https://github.com/WebDB-App/app/assets/3092780/1d8898f9-7b26-49aa-ab80-29920b7eb34c

Note: I checked the console and there are lots of errors... is Safari an issue?

<img width="954" alt="Screenshot 2024-02-12 at 1 11 08 PM" src="https://github.com/WebDB-App/app/assets/3092780/ab8b29bd-17c0-4366-b617-366714924cb5">

**Comment by WebDB-App** [comment]
Hey,

First, hanks for reporting issue
The console error concern monaco clipboard, nothing related to connections

I'm investigating the problem
