### ISSUE TITLE
Can't open MariaDB database

### ISSUE THREAD

**Issue by NeoMatrixJR** [WebDB-App/app#21]
All databases get stuck "loading".
Error in docker container logs:
`
select routine_name as name, routine_type as type, routine_schema as 'database' from information_schema.routines where routine_schema != 'sys' order by routine_name
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: routines is not iterable
    at MySQL.getComplexes (file:///usr/src/app/src/wrapper/mysql.js:230:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Controller.getStructure (file:///usr/src/app/src/endpoint/server/controller.js:65:24)`

**Comment by WebDB-App** [comment]
Hey,

Can you tell me which db version are you using please

**Comment by WebDB-App** [comment]
Can you run the query `SELECT routine_name as name, routine_type as type, routine_schema as 'database' FROM information_schema.routines WHERE routine_schema != 'sys' ORDER BY routine_name;` with the same credentials you used with WebDB and give me the result please

**Comment by NeoMatrixJR** [comment]
Got:
`[Cannot load from mysql.proc. The table is probably corrupted](https://stackoverflow.com/questions/27918764/cannot-load-from-mysql-proc-the-table-is-probably-corrupted)`
Ran:
`mysql_upgrade`
seems to be fixed now.

Is there a place to add users to a database?

**Comment by WebDB-App** [comment]
Great for the fix,

Sorry but not at the time, the permission part is not really in the development scope
