### ISSUE TITLE
Error loading database because there is an error in mysql procedure

### ISSUE THREAD

**Issue by herliansyah** [WebDB-App/app#44]
Error loading database because there is an error in mysql procedure

This is the error log from docker logs:

webdb-1  |  3306                sales show create procedure `maxmemoryused`
webdb-1  | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
webdb-1  | TypeError: Cannot read properties of undefined (reading 'Create Procedure')
webdb-1  |     at MySQL.getComplexes (file:///usr/src/app/src/wrapper/mysql.js:239:27)
webdb-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
webdb-1  |     at async file:///usr/src/app/src/endpoint/server/controller.js:66:23
webdb-1  | TypeError: Cannot read properties of undefined (reading 'Create Procedure')
webdb-1  |     at MySQL.getComplexes (file:///usr/src/app/src/wrapper/mysql.js:239:27)
webdb-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
webdb-1  |     at async file:///usr/src/app/src/endpoint/server/controller.js:66:23
webdb-1  | Exiting WebDB

**Comment by aleluff** [comment]
Hello, can you send me the db structure and the broken procedure

**Comment by herliansyah** [comment]
on my mysql server there is a database with mysql procedure error and if i open it the error looks like this:

```sql
SHOW CREATE PROCEDURE `sales`.`MaxMemoryUsed`;
/* SQL Error (1457): Failed to load routine sales.MaxMemoryUsed. The table mysql.proc is missing, corrupt, or contains bad data (internal code -6) */
```

when i open the database with other mysql db management like heidisql and other..error only show when i click the prcedure but the database still load normally, but if i open database with WebDB-App the database opening stuck.

**Comment by aleluff** [comment]
Often it' cause by an upgrade of the mysql server
Can you try to export from the old version and import into the new

**Comment by aleluff** [comment]
In the same time I will try to fix the bug

**Comment by aleluff** [comment]
It's pushed now, available in 15 min
