### ISSUE TITLE
inverted relations ui

### ISSUE THREAD

**Issue by 111100001** [WebDB-App/app#46]
![image](https://github.com/user-attachments/assets/375a6e48-fa19-4953-bada-09a74b89034d)

took me a long time to set up a relationship because i wanted to reference the pk of users table as an fk to accounts table.
the reason it was confusing is because the ui says "source" which i thought is the source of the reference which is users table and destination is the accounts table,

but that gave me an error and decided maybe i should reverse it and it worked

**Comment by aleluff** [comment]
So you suggest to invert source and destination?
Maybe a reword because majority of users use source as the parent / referencing.

Gemini propose me referencing / parent

What's your opinion about it ?

**Comment by 111100001** [comment]
yes exactly.

**Comment by aleluff** [comment]
So which one : referencing or parent
The destination would be referenced or child

**Comment by aleluff** [comment]
I would go for parent / child

The problem with reference(d/ing) is the word is to close and too long

Good for you ?

**Comment by 111100001** [comment]
parent child is more easily understood imo 

but i dont know the standard naming in the DB community. i was just doing my school project

**Comment by aleluff** [comment]
Dam, Postgre use parent child for another feature ...
I will go with table, column, referenced table, referenced column
This terminology comes from MySQL and is the best compromise in my opinion

**Comment by aleluff** [comment]
Pushed. I let you close the issue once validated
