### ISSUE TITLE
MariaDB view errors caused by `.`

### ISSUE THREAD

**Issue by Overlorder0** [WebDB-App/app#47]
Hi, been really enjoying your product while working with a personal MariaDB database for uni, but one issue popped up.
My tables are filled with abbreviations using full stops like "Exec. manager", "ins. skills" etc.
And when such cells are being selected into view tables they work perfectly fine in something like DBeaver, but here, because of product specifics I guess, they are broken by punctuation marks, separating strings.

So cell data like "Ex. manager" is percieved as `Ex`.`manager`,

or "mod. date" as `mod`.`date`,
also, when full stop is the last character in cell string it seems to be included in string length, yet abscent from the querry itself

Like "Setting min." as `Setting min`.``,
<img width="335" alt="Снимок экрана (8)" src="https://github.com/user-attachments/assets/9e4ffe31-95b5-4078-8ca0-75fc38411413" />

**Comment by WebDB-App** [comment]
Hey, thanks for the report

I just push the fix

I let you close the issue once validated

Best
